# Generated by Django 6.0.5 on 2026-05-09 11:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('total_collected', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('minutes_summary', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=50)),
                ('avatar', models.CharField(max_length=10)),
                ('savings_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('loan_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgendaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_items', to='api.meeting')),
            ],
        ),
        migrations.AddField(
            model_name='meeting',
            name='attendees',
            field=models.ManyToManyField(related_name='meetings_attended', to='api.member'),
        ),
        migrations.CreateModel(
            name='SHGGroup',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('bank_account', models.CharField(max_length=50)),
                ('formed', models.DateField()),
                ('total_savings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_loan_given', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_loan_repaid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('interest_earned', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('meeting_day', models.CharField(max_length=20)),
                ('meeting_frequency', models.CharField(max_length=20)),
                ('monthly_savings_target', models.DecimalField(decimal_places=2, max_digits=10)),
                ('members', models.ManyToManyField(related_name='groups', to='api.member')),
            ],
        ),
        migrations.AddField(
            model_name='meeting',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.shggroup'),
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tenure_months', models.IntegerField()),
                ('purpose', models.TextField()),
                ('applied_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.member')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.shggroup')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tenure_months', models.IntegerField()),
                ('amount_repaid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('disbursed_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=20)),
                ('purpose', models.TextField()),
                ('approved_by', models.CharField(max_length=100)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.member')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.shggroup')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('approved_by', models.CharField(max_length=100)),
                ('receipt_no', models.CharField(max_length=50)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.shggroup')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.member')),
            ],
        ),
    ]
