# Generated by Django 6.0.5 on 2026-05-16 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_otpverification_alter_agendaitem_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OTPVerification',
            new_name='OTP',
        ),
        migrations.AlterModelOptions(
            name='otp',
            options={},
        ),
        migrations.RenameField(
            model_name='otp',
            old_name='otp',
            new_name='otp_code',
        ),
    ]
